version: '3'

services:
  direwolf:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    container_name: direwolf
    volumes:
      - ./direwolf.conf:/direwolf/direwolf.conf
    devices:
      - /dev/snd:/dev/snd
      - /dev/gpiomem:/dev/gpiomem
    restart: unless-stopped
